name: "CICD for python"

on:
    push:
        branches:
            - "main"

jobs:
    build:
        runs-on: ubuntu-latest
        
        strategy:
            matrix:
                python-version: [3.8,3.9]
        steps:
            - name: Check out branch
              uses: actions/checkout@v4 

            - name: Set up Python
              uses: actions/setup-python@v5